### YamlMime:ManagedReference
items:
  - uid: com.microsoft.azure.batch._create_tasks_error_exception
    id: _create_tasks_error_exception
    parent: com.microsoft.azure.batch
    children:
      - 'com.microsoft.azure.batch._create_tasks_error_exception.CreateTasksErrorException(final String,List<TaskAddResult>,List<TaskAddParameter>)'
      - com.microsoft.azure.batch._create_tasks_error_exception.failureTaskList()
      - com.microsoft.azure.batch._create_tasks_error_exception.pendingTaskList()
    href: com.microsoft.azure.batch._create_tasks_error_exception.yml
    langs:
      - java
    name: CreateTasksErrorException
    nameWithType: CreateTasksErrorException
    fullName: com.microsoft.azure.batch.CreateTasksErrorException
    type: Class
    source:
      remote: &ref_0
        path: src/main/java/com/microsoft/azure/batch/CreateTasksErrorException.java
        branch: master
        repo: 'https://github.com/Azure/azure-batch-sdk-for-java'
      path: src/main/java/com/microsoft/azure/batch/CreateTasksErrorException.java
      startLine: 19
    package: com.microsoft.azure.batch
    summary: '<p><span data-ttu-id="e3b0f-101">Die Ausnahme ausgelöst, wenn ist die <xref uid="" data-throw-if-not-resolved="false">TaskOperations #CreateTasks(String, List)</xref> Vorgang wird beendet.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-101">The exception that is thrown when the <xref uid="" data-throw-if-not-resolved="false">TaskOperations#createTasks(String, List)</xref> operation is terminated.</span></span> </p>'
    syntax: &ref_1
      content: public class CreateTasksErrorException extends BatchErrorException
    inheritance:
      - java.lang.Object
      - RestException
      - com.microsoft.azure.batch.protocol.models._batch_error_exception
    inheritedMembers:
      - 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>)'
      - 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>,final BatchError)'
      - com.microsoft.azure.batch.protocol.models._batch_error_exception.body()
  - uid: 'com.microsoft.azure.batch._create_tasks_error_exception.CreateTasksErrorException(final String,List<TaskAddResult>,List<TaskAddParameter>)'
    id: 'CreateTasksErrorException(final String,List<TaskAddResult>,List<TaskAddParameter>)'
    parent: com.microsoft.azure.batch._create_tasks_error_exception
    href: com.microsoft.azure.batch._create_tasks_error_exception.yml
    langs:
      - java
    name: 'CreateTasksErrorException(final String message, List<TaskAddResult> failureTaskList, List<TaskAddParameter> pendingTaskList)'
    nameWithType: 'CreateTasksErrorException.CreateTasksErrorException(final String message, List<TaskAddResult> failureTaskList, List<TaskAddParameter> pendingTaskList)'
    fullName: 'com.microsoft.azure.batch.CreateTasksErrorException.CreateTasksErrorException(final String message, List<TaskAddResult> failureTaskList, List<TaskAddParameter> pendingTaskList)'
    overload: com.microsoft.azure.batch._create_tasks_error_exception.CreateTasksErrorException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/main/java/com/microsoft/azure/batch/CreateTasksErrorException.java
      startLine: 28
    package: com.microsoft.azure.batch
    summary: |-
      <p><span data-ttu-id="e3b0f-102">Initialisiert eine neue Instanz der dem <xref uid="com.microsoft.azure.batch._create_tasks_error_exception" data-throw-if-not-resolved="false">CreateTasksErrorException</xref> Klasse.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-102">Initializes a new instance of the <xref uid="com.microsoft.azure.batch._create_tasks_error_exception" data-throw-if-not-resolved="false">CreateTasksErrorException</xref> class.</span></span></p>
      <p></p>
    syntax:
      content: 'public CreateTasksErrorException(final String message, List<TaskAddResult> failureTaskList, List<TaskAddParameter> pendingTaskList)'
      parameters:
        - id: message
          type: 3d93591e
          description: <p><span data-ttu-id="e3b0f-103">Die Ausnahmemeldung.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-103">The exception message.</span></span> </p>
        - id: failureTaskList
          type: 5618da2dcom.microsoft.azure.batch.protocol.models._task_add_resulta08ddfce
          description: '<p><span data-ttu-id="e3b0f-104">Die Liste der <xref uid="" data-throw-if-not-resolved="false">TaskAddResult</xref> Instanzen enthält Fehlerdetails für Aufgaben, die nicht erfolgreich erstellt wurden.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-104">The list of <xref uid="" data-throw-if-not-resolved="false">TaskAddResult</xref> instances containing failure details for tasks that were not successfully created.</span></span> </p>'
        - id: pendingTaskList
          type: 5618da2dcom.microsoft.azure.batch.protocol.models._task_add_parametera08ddfce
          description: '<p><span data-ttu-id="e3b0f-105">Die Liste der <xref uid="" data-throw-if-not-resolved="false">TaskAddParameter</xref> Instanzen mit Aufgaben, die nicht hinzugefügt, aber für die der Vorgang wiederholt werden kann.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-105">The list of <xref uid="" data-throw-if-not-resolved="false">TaskAddParameter</xref> instances containing the tasks that were not added, but for which the operation can be retried.</span></span> </p>'
  - uid: com.microsoft.azure.batch._create_tasks_error_exception.failureTaskList()
    id: failureTaskList()
    parent: com.microsoft.azure.batch._create_tasks_error_exception
    href: com.microsoft.azure.batch._create_tasks_error_exception.yml
    langs:
      - java
    name: failureTaskList()
    nameWithType: CreateTasksErrorException.failureTaskList()
    fullName: List<TaskAddResult> com.microsoft.azure.batch.CreateTasksErrorException.failureTaskList()
    overload: com.microsoft.azure.batch._create_tasks_error_exception.failureTaskList*
    type: Method
    source:
      remote: *ref_0
      path: src/main/java/com/microsoft/azure/batch/CreateTasksErrorException.java
      startLine: 41
    package: com.microsoft.azure.batch
    syntax:
      content: public List<TaskAddResult> failureTaskList()
      return:
        type: 5618da2dcom.microsoft.azure.batch.protocol.models._task_add_resulta08ddfce
        description: '<p><span data-ttu-id="e3b0f-106">Die Liste der <xref uid="" data-throw-if-not-resolved="false">TaskAddResult</xref> Instanzen enthält Fehlerdetails für Aufgaben, die nicht erfolgreich erstellt wurden.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-106">The list of <xref uid="" data-throw-if-not-resolved="false">TaskAddResult</xref> instances containing failure details for tasks that were not successfully created.</span></span> </p>'
  - uid: com.microsoft.azure.batch._create_tasks_error_exception.pendingTaskList()
    id: pendingTaskList()
    parent: com.microsoft.azure.batch._create_tasks_error_exception
    href: com.microsoft.azure.batch._create_tasks_error_exception.yml
    langs:
      - java
    name: pendingTaskList()
    nameWithType: CreateTasksErrorException.pendingTaskList()
    fullName: List<TaskAddParameter> com.microsoft.azure.batch.CreateTasksErrorException.pendingTaskList()
    overload: com.microsoft.azure.batch._create_tasks_error_exception.pendingTaskList*
    type: Method
    source:
      remote: *ref_0
      path: src/main/java/com/microsoft/azure/batch/CreateTasksErrorException.java
      startLine: 48
    package: com.microsoft.azure.batch
    syntax:
      content: public List<TaskAddParameter> pendingTaskList()
      return:
        type: 5618da2dcom.microsoft.azure.batch.protocol.models._task_add_parametera08ddfce
        description: '<p><span data-ttu-id="e3b0f-107">Die Liste der <xref uid="" data-throw-if-not-resolved="false">TaskAddParameter</xref> Instanzen mit Aufgaben, die nicht hinzugefügt, aber für die der Vorgang wiederholt werden kann.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-107">The list of <xref uid="" data-throw-if-not-resolved="false">TaskAddParameter</xref> instances containing the tasks that were not added, but for which the operation can be retried.</span></span> </p>'
references:
  - uid: 3d93591e
    spec.java:
      - name: final String
        fullName: final String
  - uid: 5618da2dcom.microsoft.azure.batch.protocol.models._task_add_resulta08ddfce
    spec.java:
      - name: List<
        fullName: List<
      - uid: com.microsoft.azure.batch.protocol.models._task_add_result
        name: TaskAddResult
        fullName: com.microsoft.azure.batch.protocol.models.TaskAddResult
        href: com.microsoft.azure.batch.protocol.models._task_add_result.yml
      - name: '>'
        fullName: '>'
  - uid: 5618da2dcom.microsoft.azure.batch.protocol.models._task_add_parametera08ddfce
    spec.java:
      - name: List<
        fullName: List<
      - uid: com.microsoft.azure.batch.protocol.models._task_add_parameter
        name: TaskAddParameter
        fullName: com.microsoft.azure.batch.protocol.models.TaskAddParameter
        href: com.microsoft.azure.batch.protocol.models._task_add_parameter.yml
      - name: '>'
        fullName: '>'
  - uid: com.microsoft.azure.batch._create_tasks_error_exception.CreateTasksErrorException*
    name: CreateTasksErrorException
    nameWithType: CreateTasksErrorException.CreateTasksErrorException
    fullName: com.microsoft.azure.batch.CreateTasksErrorException.CreateTasksErrorException
    package: com.microsoft.azure.batch
  - uid: com.microsoft.azure.batch._create_tasks_error_exception.failureTaskList*
    name: failureTaskList
    nameWithType: CreateTasksErrorException.failureTaskList
    fullName: List<TaskAddResult> com.microsoft.azure.batch.CreateTasksErrorException.failureTaskList
    package: com.microsoft.azure.batch
  - uid: com.microsoft.azure.batch._create_tasks_error_exception.pendingTaskList*
    name: pendingTaskList
    nameWithType: CreateTasksErrorException.pendingTaskList
    fullName: List<TaskAddParameter> com.microsoft.azure.batch.CreateTasksErrorException.pendingTaskList
    package: com.microsoft.azure.batch
  - uid: 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>)'
    parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    name: 'BatchErrorException(final String message, final Response<ResponseBody> response)'
    nameWithType: 'BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response)'
    fullName: 'com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response)'
    type: Constructor
    summary: |-
      <p><span data-ttu-id="e3b0f-108">Initialisiert eine neue Instanz der dem <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref> Klasse.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-108">Initializes a new instance of the <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref> class.</span></span></p>
      <p></p>
    syntax:
      content: 'public BatchErrorException(final String message, final Response<ResponseBody> response)'
      parameters:
        - id: message
          type: 3d93591e
          description: '<p><span data-ttu-id="e3b0f-109">die Ausnahmemeldung oder des Inhalts der Antwort, wenn eine Nachricht nicht verfügbar ist.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-109">the exception message or the response content if a message is not available</span></span> </p>'
        - id: response
          type: 4f402e61
          description: <p><span data-ttu-id="e3b0f-110">die HTTP-Antwort</span><span class="sxs-lookup"><span data-stu-id="e3b0f-110">the HTTP response</span></span> </p>
  - uid: 'com.microsoft.azure.batch.protocol.models._batch_error_exception.BatchErrorException(final String,final Response<ResponseBody>,final BatchError)'
    parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    name: 'BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
    nameWithType: 'BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
    fullName: 'com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
    type: Constructor
    summary: |-
      <p><span data-ttu-id="e3b0f-111">Initialisiert eine neue Instanz der dem <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref> Klasse.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-111">Initializes a new instance of the <xref uid="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false">BatchErrorException</xref> class.</span></span></p>
      <p></p>
    syntax:
      content: 'public BatchErrorException(final String message, final Response<ResponseBody> response, final BatchError body)'
      parameters:
        - id: message
          type: 3d93591e
          description: '<p><span data-ttu-id="e3b0f-112">die Ausnahmemeldung oder des Inhalts der Antwort, wenn eine Nachricht nicht verfügbar ist.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-112">the exception message or the response content if a message is not available</span></span> </p>'
        - id: response
          type: 4f402e61
          description: <p><span data-ttu-id="e3b0f-113">die HTTP-Antwort</span><span class="sxs-lookup"><span data-stu-id="e3b0f-113">the HTTP response</span></span> </p>
        - id: body
          type: 93de0ef9com.microsoft.azure.batch.protocol.models._batch_error
          description: <p><span data-ttu-id="e3b0f-114">der deserialisierte Antworttext</span><span class="sxs-lookup"><span data-stu-id="e3b0f-114">the deserialized response body</span></span> </p>
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception.body()
    parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    name: body()
    nameWithType: BatchErrorException.body()
    fullName: BatchError com.microsoft.azure.batch.protocol.models.BatchErrorException.body()
    type: Method
    syntax:
      content: public BatchError body()
      return:
        type: com.microsoft.azure.batch.protocol.models._batch_error
  - uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
    parent: com.microsoft.azure.batch.protocol.models
    href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
    name: BatchErrorException
    nameWithType: BatchErrorException
    fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
    type: Class
    summary: <p><span data-ttu-id="e3b0f-115">Ausgelöste Ausnahme für eine ungültige Antwort mit <xref uid="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false">BatchError</xref> Informationen.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-115">Exception thrown for an invalid response with <xref uid="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false">BatchError</xref> information.</span></span> </p>
    syntax:
      content: public class BatchErrorException
  - uid: com.microsoft.azure.batch.protocol.models._task_add_result
    parent: com.microsoft.azure.batch.protocol.models
    href: com.microsoft.azure.batch.protocol.models._task_add_result.yml
    name: TaskAddResult
    nameWithType: TaskAddResult
    fullName: com.microsoft.azure.batch.protocol.models.TaskAddResult
    type: Class
    summary: '<p><span data-ttu-id="e3b0f-116">Auslöser für eine einzelne Aufgabe, die als Teil einer Auflistung Vorgangs zum Hinzufügen eines Tasks hinzugefügt.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-116">Result for a single task added as part of an add task collection operation.</span></span> </p>'
    syntax:
      content: public class TaskAddResult
  - uid: com.microsoft.azure.batch.protocol.models._task_add_parameter
    parent: com.microsoft.azure.batch.protocol.models
    href: com.microsoft.azure.batch.protocol.models._task_add_parameter.yml
    name: TaskAddParameter
    nameWithType: TaskAddParameter
    fullName: com.microsoft.azure.batch.protocol.models.TaskAddParameter
    type: Class
    summary: <p><span data-ttu-id="e3b0f-117">Ein hinzuzufügende Azure Batch-Aufgabe.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-117">An Azure Batch task to add.</span></span> </p>
    syntax:
      content: public class TaskAddParameter
  - uid: com.microsoft.azure.batch._create_tasks_error_exception
    parent: com.microsoft.azure.batch
    href: com.microsoft.azure.batch._create_tasks_error_exception.yml
    name: CreateTasksErrorException
    nameWithType: CreateTasksErrorException
    fullName: com.microsoft.azure.batch.CreateTasksErrorException
    type: Class
    summary: '<p><span data-ttu-id="e3b0f-118">Die Ausnahme ausgelöst, wenn ist die <xref uid="" data-throw-if-not-resolved="false">TaskOperations #CreateTasks(String, List)</xref> Vorgang wird beendet.</span><span class="sxs-lookup"><span data-stu-id="e3b0f-118">The exception that is thrown when the <xref uid="" data-throw-if-not-resolved="false">TaskOperations#createTasks(String, List)</xref> operation is terminated.</span></span> </p>'
    syntax: *ref_1