### YamlMime:ManagedReference
items:
  - uid: system.fabric.exception._duplicate_message_exception
    id: _duplicate_message_exception
    parent: system.fabric.exception
    children:
      - system.fabric.exception._duplicate_message_exception.DuplicateMessageException()
      - system.fabric.exception._duplicate_message_exception.DuplicateMessageException(String)
      - 'system.fabric.exception._duplicate_message_exception.DuplicateMessageException(String,Throwable)'
      - 'system.fabric.exception._duplicate_message_exception.DuplicateMessageException(String,Throwable,boolean,boolean)'
      - system.fabric.exception._duplicate_message_exception.DuplicateMessageException(Throwable)
    href: system.fabric.exception._duplicate_message_exception.yml
    langs:
      - java
    name: DuplicateMessageException
    nameWithType: DuplicateMessageException
    fullName: system.fabric.exception.DuplicateMessageException
    type: Class
    source:
      remote: &ref_0
        path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
        branch: master
        repo: 'https://msazure.visualstudio.com/One/_git/sf-java'
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
      startLine: 3
    package: system.fabric.exception
    summary: '<p><span data-ttu-id="a07b8-101">Ausnahme gibt an, dass Akteur doppelte Nachricht empfangen</span><span class="sxs-lookup"><span data-stu-id="a07b8-101">Exception indicates that Actor recieved Duplicate Message</span></span> </p>'
    syntax: &ref_1
      content: public class DuplicateMessageException extends FabricException
    inheritance:
      - java.lang.Object
      - RuntimeException
      - system.fabric.exception._fabric_exception
    inheritedMembers:
      - system.fabric.exception._fabric_exception.FabricException()
      - system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
      - system.fabric.exception._fabric_exception.FabricException(String)
      - 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.FabricException(Throwable)
      - 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
      - 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
      - system.fabric.exception._fabric_exception.getErrorCode()
  - uid: system.fabric.exception._duplicate_message_exception.DuplicateMessageException()
    id: DuplicateMessageException()
    parent: system.fabric.exception._duplicate_message_exception
    href: system.fabric.exception._duplicate_message_exception.yml
    langs:
      - java
    name: DuplicateMessageException()
    nameWithType: DuplicateMessageException.DuplicateMessageException()
    fullName: system.fabric.exception.DuplicateMessageException.DuplicateMessageException()
    overload: system.fabric.exception._duplicate_message_exception.DuplicateMessageException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
      startLine: 11
    package: system.fabric.exception
    summary: <p><span data-ttu-id="a07b8-102">Initialisiert eine neue Instanz der dem <xref uid="system.fabric.exception._duplicate_message_exception" data-throw-if-not-resolved="false">DuplicateMessageException</xref> Klasse.</span><span class="sxs-lookup"><span data-stu-id="a07b8-102">Initializes a new instance of the <xref uid="system.fabric.exception._duplicate_message_exception" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class.</span></span> </p>
    syntax:
      content: public DuplicateMessageException()
  - uid: system.fabric.exception._duplicate_message_exception.DuplicateMessageException(String)
    id: DuplicateMessageException(String)
    parent: system.fabric.exception._duplicate_message_exception
    href: system.fabric.exception._duplicate_message_exception.yml
    langs:
      - java
    name: DuplicateMessageException(String message)
    nameWithType: DuplicateMessageException.DuplicateMessageException(String message)
    fullName: system.fabric.exception.DuplicateMessageException.DuplicateMessageException(String message)
    overload: system.fabric.exception._duplicate_message_exception.DuplicateMessageException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
      startLine: 36
    package: system.fabric.exception
    summary: |-
      <p><span data-ttu-id="a07b8-103">Initialisiert eine neue Instanz der dem <xref uid="system.fabric.exception._duplicate_message_exception" data-throw-if-not-resolved="false">DuplicateMessageException</xref> Klasse mit einer angegebenen Fehlermeldung.</span><span class="sxs-lookup"><span data-stu-id="a07b8-103">Initializes a new instance of the <xref uid="system.fabric.exception._duplicate_message_exception" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class with a specified error message.</span></span></p>
      <p></p>
    syntax:
      content: public DuplicateMessageException(String message)
      parameters:
        - id: message
          type: '26831127'
          description: <p><span data-ttu-id="a07b8-104">Eingabenachricht</span><span class="sxs-lookup"><span data-stu-id="a07b8-104">input message</span></span> </p>
  - uid: 'system.fabric.exception._duplicate_message_exception.DuplicateMessageException(String,Throwable)'
    id: 'DuplicateMessageException(String,Throwable)'
    parent: system.fabric.exception._duplicate_message_exception
    href: system.fabric.exception._duplicate_message_exception.yml
    langs:
      - java
    name: 'DuplicateMessageException(String message, Throwable cause)'
    nameWithType: 'DuplicateMessageException.DuplicateMessageException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.DuplicateMessageException.DuplicateMessageException(String message, Throwable cause)'
    overload: system.fabric.exception._duplicate_message_exception.DuplicateMessageException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
      startLine: 25
    package: system.fabric.exception
    summary: |-
      <p><span data-ttu-id="a07b8-105">Initialisiert eine neue Instanz der dem <xref uid="system.fabric.exception._duplicate_message_exception" data-throw-if-not-resolved="false">DuplicateMessageException</xref> Klasse mit einer angegebenen Fehlermeldung und einem Verweis auf die innere Ausnahme, die diese Ausnahme ausgelöst hat.</span><span class="sxs-lookup"><span data-stu-id="a07b8-105">Initializes a new instance of the <xref uid="system.fabric.exception._duplicate_message_exception" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></p>
      <p></p>
    syntax:
      content: 'public DuplicateMessageException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
          description: '<p><span data-ttu-id="a07b8-106">Die Fehlermeldung, die die Ursache der Ausnahme erklärt wird.</span><span class="sxs-lookup"><span data-stu-id="a07b8-106">The error message that explains the reason for the exception.</span></span> </p>'
        - id: cause
          type: a04fafd7
          description: '<p><span data-ttu-id="a07b8-107">Die Ausnahme, die die Ursache für die aktuelle Ausnahme oder ein null-Verweis ist, wenn keine innere Ausnahme angegeben wird.</span><span class="sxs-lookup"><span data-stu-id="a07b8-107">The exception that is the cause of the current exception, or a null reference if no inner exception is specified.</span></span> </p>'
  - uid: 'system.fabric.exception._duplicate_message_exception.DuplicateMessageException(String,Throwable,boolean,boolean)'
    id: 'DuplicateMessageException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._duplicate_message_exception
    href: system.fabric.exception._duplicate_message_exception.yml
    langs:
      - java
    name: 'DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'DuplicateMessageException.DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.DuplicateMessageException.DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    overload: system.fabric.exception._duplicate_message_exception.DuplicateMessageException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
      startLine: 44
    package: system.fabric.exception
    syntax:
      content: 'protected DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: system.fabric.exception._duplicate_message_exception.DuplicateMessageException(Throwable)
    id: DuplicateMessageException(Throwable)
    parent: system.fabric.exception._duplicate_message_exception
    href: system.fabric.exception._duplicate_message_exception.yml
    langs:
      - java
    name: DuplicateMessageException(Throwable cause)
    nameWithType: DuplicateMessageException.DuplicateMessageException(Throwable cause)
    fullName: system.fabric.exception.DuplicateMessageException.DuplicateMessageException(Throwable cause)
    overload: system.fabric.exception._duplicate_message_exception.DuplicateMessageException*
    type: Constructor
    source:
      remote: *ref_0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/DuplicateMessageException.java
      startLine: 40
    package: system.fabric.exception
    syntax:
      content: public DuplicateMessageException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
references:
  - uid: system.fabric.exception._duplicate_message_exception.DuplicateMessageException*
    name: DuplicateMessageException
    nameWithType: DuplicateMessageException.DuplicateMessageException
    fullName: system.fabric.exception.DuplicateMessageException.DuplicateMessageException
    package: system.fabric.exception
  - uid: '26831127'
    spec.java:
      - name: String
        fullName: String
  - uid: a04fafd7
    spec.java:
      - name: Throwable
        fullName: Throwable
  - uid: 4fc6e284
    spec.java:
      - name: boolean
        fullName: boolean
  - uid: system.fabric.exception._fabric_exception.FabricException()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException()
    nameWithType: FabricException.FabricException()
    fullName: system.fabric.exception.FabricException.FabricException()
    type: Constructor
    syntax:
      content: public FabricException()
  - uid: system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(FabricErrorCode errorCode)
    nameWithType: FabricException.FabricException(FabricErrorCode errorCode)
    fullName: system.fabric.exception.FabricException.FabricException(FabricErrorCode errorCode)
    type: Constructor
    syntax:
      content: public FabricException(FabricErrorCode errorCode)
      parameters:
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(String)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(String message)
    nameWithType: FabricException.FabricException(String message)
    fullName: system.fabric.exception.FabricException.FabricException(String message)
    type: Constructor
    syntax:
      content: public FabricException(String message)
      parameters:
        - id: message
          type: '26831127'
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(String message, Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.FabricException(Throwable)
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException(Throwable cause)
    nameWithType: FabricException.FabricException(Throwable cause)
    fullName: system.fabric.exception.FabricException.FabricException(Throwable cause)
    type: Constructor
    syntax:
      content: public FabricException(Throwable cause)
      parameters:
        - id: cause
          type: a04fafd7
  - uid: 'system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(Throwable cause, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'public FabricException(Throwable cause, FabricErrorCode errorCode)'
      parameters:
        - id: cause
          type: a04fafd7
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
  - uid: 'system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)'
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: 'FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    nameWithType: 'FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    fullName: 'system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
    type: Constructor
    syntax:
      content: 'protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)'
      parameters:
        - id: message
          type: '26831127'
        - id: cause
          type: a04fafd7
        - id: enableSuppression
          type: 4fc6e284
        - id: writableStackTrace
          type: 4fc6e284
        - id: errorCode
          type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception.getErrorCode()
    parent: system.fabric.exception._fabric_exception
    href: system.fabric.exception._fabric_exception.yml
    name: getErrorCode()
    nameWithType: FabricException.getErrorCode()
    fullName: FabricErrorCode system.fabric.exception.FabricException.getErrorCode()
    type: Method
    syntax:
      content: public FabricErrorCode getErrorCode()
      return:
        type: system.fabric._fabric_error_code
  - uid: system.fabric.exception._fabric_exception
    parent: system.fabric.exception
    href: system.fabric.exception._fabric_exception.yml
    name: FabricException
    nameWithType: FabricException
    fullName: system.fabric.exception.FabricException
    type: Class
    syntax:
      content: public class FabricException
  - uid: system.fabric.exception._duplicate_message_exception
    parent: system.fabric.exception
    href: system.fabric.exception._duplicate_message_exception.yml
    name: DuplicateMessageException
    nameWithType: DuplicateMessageException
    fullName: system.fabric.exception.DuplicateMessageException
    type: Class
    summary: '<p><span data-ttu-id="a07b8-108">Ausnahme gibt an, dass Akteur doppelte Nachricht empfangen</span><span class="sxs-lookup"><span data-stu-id="a07b8-108">Exception indicates that Actor recieved Duplicate Message</span></span> </p>'
    syntax: *ref_1